# Generated by Django 2.0.3 on 2018-08-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='teamname',
            field=models.CharField(default='solo', max_length=50),
        ),
    ]
