# Generated by Django 2.0.3 on 2018-08-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180812_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregister',
            name='teamname',
            field=models.CharField(max_length=50),
        ),
    ]
