# Generated by Django 2.0.3 on 2018-08-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_officebearers'),
    ]

    operations = [
        migrations.AddField(
            model_name='officebearers',
            name='social_media',
            field=models.CharField(default='https://www.fb.com', max_length=200),
        ),
    ]
