# Generated by Django 2.1 on 2018-08-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
