# Generated by Django 2.0.3 on 2018-08-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20180820_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officebearers',
            name='image',
            field=models.ImageField(upload_to='Canoe/static/img'),
        ),
    ]
